# Generated by Django 3.1.4 on 2020-12-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_number',
            field=models.IntegerField(default=0),
        ),
    ]
