# Generated by Django 3.1.4 on 2020-12-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201229_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='login_number',
        ),
    ]
